name: Python 3.11
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        make install
    - name: Run the main.py file
      run: |
        make run
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test the main.py file
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
